# Generated by Django 6.0.2 on 2026-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupchatread_privatechatread'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/group/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/private/', verbose_name='Изображение'),
        ),
    ]
