# Generated by Django 6.0.2 on 2026-05-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupchatmessage_image_privatemessage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatMessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat/group/gallery/', verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.groupchatmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Фотография группового сообщения',
                'verbose_name_plural': 'Фотографии группового сообщения',
            },
        ),
    ]
