# Generated by Django 6.0.2 on 2026-03-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Отдел')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
