# Generated by Django 6.0.2 on 2026-03-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('supervisor', 'Супервайзер (СВ)'), ('security', 'Служба безопасности (СБ)'), ('cashier', 'Кассир'), ('loss_prevention', 'Специалист по предотвращению потерь')], max_length=50, verbose_name='Должность'),
        ),
    ]
