# Generated by Django 6.0.2 on 2026-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('all', 'Все'), ('department', 'Мой отдел')], default='all', max_length=20, verbose_name='Кому показывать'),
        ),
    ]
