# Generated by Django 6.0.2 on 2026-05-14 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_profile_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название магазина')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Рабочий телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('worker_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_worker_account', to=settings.AUTH_USER_MODEL, verbose_name='Рабочий аккаунт магазина')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='managed_stores',
            field=models.ManyToManyField(blank=True, related_name='managers', to='feed.store', verbose_name='Доступные магазины'),
        ),
        migrations.AddField(
            model_name='profile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='feed.store', verbose_name='Основной магазин'),
        ),
    ]
