# Generated by Django 6.0.2 on 2026-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_store_profile_managed_stores_profile_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='posts', to='feed.store', verbose_name='Магазины'),
        ),
    ]
