# Generated by Django 6.0.2 on 2026-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_post_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed/posts/', verbose_name='Фотография'),
        ),
    ]
