# Generated by Django 6.0.2 on 2026-05-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feed/posts/gallery/', verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feed.post', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фотография новости',
                'verbose_name_plural': 'Фотографии новости',
            },
        ),
    ]
